#ifndef __LINUX_PCI_IDS_H
#define __LINUX_PCI_IDS_H

#define PCI_VENDOR_ID_DELL		0x1028
#define PCI_VENDOR_ID_HP		0x103c
#define PCI_VENDOR_ID_AMD		0x1022
#define PCI_VENDOR_ID_TOSHIBA		0x1179
#define PCI_VENDOR_ID_DFI		0x15bd
#define PCI_VENDOR_ID_INTEL		0x8086

#endif /* __LINUX_PCI_IDS_H */
