#define CONFIG_PROC_FS
#define CONFIG_SND_PROC_FS
#define CONFIG_SND_JACK

#define CONFIG_PM
#define CONFIG_SND_HDA_POWER_SAVE_DEFAULT	0

#define CONFIG_SND_DEBUG
#define CONFIG_SND_DEBUG_VERBOSE

#define CONFIG_SND_HDA_GENERIC
#define CONFIG_SND_HDA_HWDEP
#define CONFIG_SND_HDA_INPUT_JACK
#define CONFIG_SND_HDA_INPUT_BEEP

#define CONFIG_SND_HDA_ENABLE_REALTEK_QUIRKS

#define CONFIG_SND_DYNAMIC_MINORS
